// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsZWUziFKC7809d_Ib49vEsT84yB3ASJg',
    appId: '1:21960939027:web:0b431fb11637f25d69d1e6',
    messagingSenderId: '21960939027',
    projectId: 'unican-33d3b',
    authDomain: 'unican-33d3b.firebaseapp.com',
    databaseURL: 'https://unican-33d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unican-33d3b.firebasestorage.app',
    measurementId: 'G-0NXYZK6Q0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR-HpHeBAxZkE-hf4wa35AAvlj9s0DST4',
    appId: '1:21960939027:android:1f067c1bd18426b869d1e6',
    messagingSenderId: '21960939027',
    projectId: 'unican-33d3b',
    databaseURL: 'https://unican-33d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unican-33d3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhicYsLxry5TGp8W7CqnzI-M0Ic9dGbQ',
    appId: '1:21960939027:ios:035962146001ad5c69d1e6',
    messagingSenderId: '21960939027',
    projectId: 'unican-33d3b',
    databaseURL: 'https://unican-33d3b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'unican-33d3b.firebasestorage.app',
    iosBundleId: 'com.example.unican',
  );
}
